kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://localhost:5001"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."localhost:5001".tls]
    insecure_skip_verify = true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      name: alpha
  labels:
    topology.kubernetes.io/zone: alpha
    node.kubernetes.io/instance-type: custom-3vcpu-6gb
    node.kubernetes.io/local-storage: 30gb
  extraMounts:
  - hostPath: proxy/proxy.conf
    containerPath: /etc/systemd/system/containerd.service.d/proxy.conf
    readOnly: true
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: sigma
  labels:
    topology.kubernetes.io/zone: sigma
    node.kubernetes.io/instance-type: custom-3vcpu-6gb
    node.kubernetes.io/local-storage: 30gb
  extraMounts:
  - hostPath: proxy/proxy.conf
    containerPath: /etc/systemd/system/containerd.service.d/proxy.conf
    readOnly: true
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: gamma
  labels:
    topology.kubernetes.io/zone: gamma
    node.kubernetes.io/instance-type: custom-3vcpu-6gb
    node.kubernetes.io/local-storage: 30gb
  extraMounts:
  - hostPath: proxy/proxy.conf
    containerPath: /etc/systemd/system/containerd.service.d/proxy.conf
    readOnly: true
