grafana:
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 30080

prometheus:
  prometheusSpec:
    image:
      tag: v3.1.0
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

# Global image pull policy - use images already in Kind
global:
  imagePullPolicy: Never

# Component configurations
prometheusOperator:
  image:
    tag: v0.79.2
  imagePullPolicy: Never

alertmanager:
  alertmanagerSpec:
    image:
      tag: v0.28.1

kube-state-metrics:
  image:
    tag: v2.14.0
  imagePullPolicy: Never

prometheus-node-exporter:
  image:
    tag: v1.8.2
  imagePullPolicy: Never

admissionWebhooks:
  deployment:
    image:
      tag: v0.79.2
  patch:
    image:
      tag: v1.6.5
